spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/credit_registration
    username: root
    password: ''
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:liquibase/changelog.yml

  scheduler:
    initDelay: 120000
    fixedRate: 120000
    poolSize: 5