INSERT INTO roles (NAME)
SELECT 'ROLE_USER'
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM roles WHERE NAME = 'ROLE_USER');

INSERT INTO roles (NAME)
SELECT 'ROLE_ADMIN'
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM roles WHERE NAME = 'ROLE_ADMIN');

INSERT INTO roles (NAME)
SELECT 'ROLE_MODERATOR'
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM roles WHERE NAME = 'ROLE_MODERATOR');

INSERT INTO tariff (type, interestRate)
SELECT 'CONSUMER', '5.9%'
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM tariff WHERE type = 'CONSUMER');

INSERT INTO tariff (type, interestRate)
SELECT 'MORTGAGE', '14.1%'
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM tariff WHERE type = 'MORTGAGE');

INSERT INTO tariff (type, interestRate)
SELECT 'MICROLOANS', '7.6%'
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM tariff WHERE type = 'MICROLOANS');
